services:
  - type: web
    name: print-factory
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "python manage.py migrate && gunicorn config.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings
      - key: SECRET_KEY
        generateValue: true
