# Generated by Django 6.0.7 on 2026-08-03 17:12

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='badge',
            field=models.CharField(blank=True, default='01 / SERVICE', max_length=80),
        ),
        migrations.AddField(
            model_name='service',
            name='base_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('490.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='service',
            name='speed_info',
            field=models.CharField(blank=True, default='Standard 2-3 Days', max_length=100),
        ),
        migrations.AddField(
            model_name='service',
            name='tags_csv',
            field=models.CharField(blank=True, help_text='Comma-separated spec tags', max_length=500),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='content/services/'),
        ),
    ]
