# Generated by Django 6.0.7 on 2026-08-03 16:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinquiry',
            name='status_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contactinquiry',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_inquiries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contactinquiry',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('quote_sent', 'Quote Sent'), ('converted', 'Won / Converted'), ('closed', 'Closed / Lost')], default='new', max_length=16),
        ),
    ]
