# Generated by Django 6.0.7 on 2026-08-03 16:32

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_category_options_category_badge_category_icon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='optionvalue',
            name='price_modifier',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
