# Generated by Django 6.0.7 on 2026-08-04 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_optionvalue_price_modifier'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='catalog_pro_is_acti_1a8de5_idx',
        ),
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['is_active', 'slug'], name='catalog_cat_is_acti_1395d0_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active', 'category', 'created_at'], name='catalog_pro_is_acti_f0ce94_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['slug'], name='catalog_pro_slug_2b1eb6_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active', 'created_at'], name='catalog_pro_is_acti_00391f_idx'),
        ),
    ]
